# Server configuration
server.port=8080

# Database PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/parea
spring.datasource.username=postgres
spring.datasource.password=parea
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (Clave HMAC-SHA256 codificada en Base64 de al menos 256 bits)
application.security.jwt.secret-key=zWujL3wVoERWiWg61Ee4/5SYEnOQvqyJM2knc1zp5FA=
# Expiración en milisegundos: 86400000 ms = 24 horas
application.security.jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/parea
spring.datasource.username=postgres
spring.datasource.password=parea
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Logging configuration - logs debug de Spring Security
logging.level.org.springframework.security=DEBUG